# Generated by Django 5.2.7 on 2025-11-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('numero_contacto', models.CharField(max_length=20, verbose_name='Número de Contacto 1')),
                ('numero_contacto_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Contacto 2')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento/Estado/Región')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Cuori',
                'verbose_name_plural': 'Cuoris',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('lugar', models.CharField(max_length=255, verbose_name='Lugar')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(default='Bogotá D.C', max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(default='Cundinamarca', max_length=100, verbose_name='Departamento')),
                ('cupos', models.PositiveIntegerField(default=0, verbose_name='Cupos')),
                ('tipo_asistencia', models.CharField(choices=[('LIMITADO', 'Cupos Limitados'), ('ABIERTO', 'Ilimitado')], default='LIMITADO', max_length=10, verbose_name='Tipo de Asistencia')),
                ('dirigido_a', models.CharField(choices=[('TODOS', 'Para todos'), ('MUJERES', 'Solo mujeres'), ('HOMBRES', 'Solo hombres'), ('PAREJAS', 'Parejas'), ('INFANTES', 'Infantes')], default='TODOS', max_length=10, verbose_name='Dirigido a')),
                ('coordenadas_mapa', models.CharField(blank=True, max_length=100, verbose_name='Coordenadas de Mapa (Latitud, Longitud)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL Slug')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen Promocional')),
                ('requiere_ofrenda', models.BooleanField(default=False, verbose_name='¿Requiere Ofrenda?')),
                ('valor_ofrenda', models.IntegerField(blank=True, null=True, verbose_name='Valor de la Ofrenda en COP$')),
                ('requiere_inscripcion', models.BooleanField(default=True, verbose_name='¿Requiere Inscripción?')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Inscripción')),
                ('cuori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.cuori')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='core.evento')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('evento', 'cuori')},
            },
        ),
    ]
