# Generated by Django 5.2.7 on 2025-11-18 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL Slug')),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('tipo_contenido', models.CharField(choices=[('LECTURA', 'Lectura'), ('REFLEXION', 'Reflexión'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('ARTICULO', 'Artículo'), ('DEVOCIONAL', 'Devocional'), ('OTRO', 'Otro')], default='ARTICULO', max_length=20, verbose_name='Tipo de Contenido')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='blog/imagenes/', verbose_name='Imagen Destacada')),
                ('archivo_audio', models.FileField(blank=True, null=True, upload_to='blog/audios/', verbose_name='Archivo de Audio')),
                ('archivo_video', models.FileField(blank=True, null=True, upload_to='blog/videos/', verbose_name='Archivo de Video')),
                ('enlace_multimedia', models.URLField(blank=True, null=True, verbose_name='Enlace a Contenido Multimedia')),
                ('descripcion_breve', models.TextField(blank=True, max_length=500, verbose_name='Descripción Breve')),
                ('es_destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('esta_publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Entrada de Blog',
                'verbose_name_plural': 'Entradas de Blog',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
