# Generated by Django 5.2.7 on 2025-11-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Información Adicional'),
        ),
    ]
