# Generated by Django 5.2.7 on 2025-11-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Autores'),
        ),
    ]
